### ISSUE TITLE
Error in running RNN file

### ISSUE THREAD

**Issue by ScrapeWithYuri** [fakefakir/Stock-Return-Predictions#2]
I receive this error when running the RNN file. Please advise:

File "C:\Users\russi\PycharmProjects\Stock-Return-Predictions-master\myUtilities.py", line 29, in on_epoch_end
    if current < self.value:
TypeError: '<' not supported between instances of 'NoneType' and 'float'

**Comment by fakefakir** [comment]
I have updated the codes on RNN.py and myUtilities.py, which given MSE as the default monitor for Earlysopping.  It should work now.

**Comment by ScrapeWithYuri** [comment]
I am still receiving the same error. The code I don't understand is `current = logs.get(self.monitor)` in the myUtilities.py file. Self.monitor is a string but is being compared against `if current < self.value`.

**Comment by ScrapeWithYuri** [comment]
I think I figured it out. I needed to update `current = logs.get(self.monitor)` to `current = logs['mse']`
